config_version: 2
settings:
  colors.webpage.preferred_color_scheme:
    global: dark
  content.javascript.clipboard:
    https://github.com: access-paste
  content.notifications.enabled:
    https://www.youtube.com: false
  url.default_page:
    global: about:blank
  url.searchengines:
    global:
      DEFAULT: https://www.startpage.com/search?q={}
  url.start_pages:
    global: https://github.com
