font_family      family="Iosevka"
font_size        13
disable_ligatures never
font_features Iosevka +calt +liga
bold_font        auto
italic_font      auto
bold_italic_font auto
confirm_os_window_close 0
include current-theme.conf
