theme = "gitdark"

[editor]
scrolloff = 0
scroll-lines = 4
line-number = 'absolute'
true-color = true
color-modes = true
bufferline = 'multiple'
default-yank-register = '+'
gutters = ["diff", "diagnostics", "line-numbers", "spacer"]

[editor.soft-wrap]
enable = true

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.statusline]
center = ["version-control"]

[editor.file-picker]
hidden = false

[editor.auto-save]
focus-lost = true
after-delay.enable = true
after-delay.timeout = 60000

[editor.whitespace.characters]
space = "·"
tab = "→"
tabpad = "·"

[editor.indent-guides]
render = true
character = "▏"
skip-levels = 0
